export default [
  {
    id: 1,
    name: 'Darth Vader',
    firstAppearance: 'III Episode',
    image: `${process.env.PUBLIC_URL}/heroes/vader.png`,
    side: 'Dark Side',
    isDisplayed: true,
  },
  {
    id: 2,
    name: 'Yoda',
    firstAppearance: 'I Episode',
    image: `${process.env.PUBLIC_URL}heroes/yoda.png`,
    side: 'Light Side',
    isDisplayed: true,
  },
  {
    id: 3,
    name: 'Stormtrooper',
    firstAppearance: 'IV Episode',
    image: `${process.env.PUBLIC_URL}/heroes/stormtrooper.png`,
    side: 'Dark Side',
    isDisplayed: true,
  },
  {
    id: 4,
    name: 'C3P0',
    firstAppearance: 'I Episode',
    image: `${process.env.PUBLIC_URL}/heroes/c3po.png`,
    side: 'Light Side',
    isDisplayed: true,
  },
  {
    id: 5,
    name: 'Luke',
    firstAppearance: 'IV Episode',
    image: `${process.env.PUBLIC_URL}/heroes/luke.png`,
    side: 'Light Side',
    isDisplayed: true,
  },
  {
    id: 6,
    name: 'Emperor Palpatine',
    firstAppearance: 'III Episode',
    image: `${process.env.PUBLIC_URL}/heroes/palpatine.png`,
    side: 'Dark Side',
    isDisplayed: true,
  },
  {
    id: 7,
    name: 'R2D2',
    firstAppearance: 'III Episode',
    image: `${process.env.PUBLIC_URL}/heroes/r2d2.png`,
    side: 'Light Side',
    isDisplayed: true,
  },
  {
    id: 8,
    name: 'Boba Fett',
    firstAppearance: 'II Episode',
    image: `${process.env.PUBLIC_URL}/heroes/boba.png`,
    side: 'Dark Side',
    isDisplayed: true,
  },
  {
    id: 9,
    name: 'Princess Leya',
    firstAppearance: 'IV Episode',
    image: `${process.env.PUBLIC_URL}/heroes/leya.png`,
    side: 'Light Side',
    isDisplayed: false,
  },
  {
    id: 10,
    name: 'Han Solo',
    firstAppearance: 'IV Episode',
    image: `${process.env.PUBLIC_URL}/heroes/solo.png`,
    side: 'Light Side',
    isDisplayed: false,
  },
  {
    id: 11,
    name: 'Chewbakka',
    firstAppearance: 'IV Episode',
    image: `${process.env.PUBLIC_URL}/heroes/chewbakka.png`,
    side: 'Light Side',
    isDisplayed: false,
  },
];
